version: "3"
services:
  mainapi:
   build: ./mainAPID/
   restart: always
   #volumes:
   #  - ./vapi:/api
   ports:
      - "1800:1800"
   links:
      - db
   depends_on:
      - db
  db:
    build: ./DB
    restart: always
    #volumes:
    #  - ./vpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  server:
    build: ./serverD/
    restart: always
    #volumes:
    #    - ./vserver:/server
    ports:
      - "1801:1801"

  client:
    build: ./clientD/
    restart: always
    #volumes:
    #    - ./vclient:/clinet
    ports:
      - "80:80"


