version: "3"
services:
  mainapi:
   build: ./mainAPID/
   ports:
      - "1800:1800"
   links:
      - db
   depends_on:
      - db
  db:
    build: ./DB
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  server:
    build: ./serverD/
    ports:
      - "1800:1800"

  client:
    build: ./clientD/
    ports:
      - "80:80"