version: "3"
services:
  mainapi:
   build: ./mainAPID/
   restart: always
   ports:
      - "1800:1800"
  db:
   image: postgres:10
   env_file: .env
   expose:
     - 5432
  server:
    build: ./serverD/
    restart: always
    ports:
      - "1801:1801"

  client:
    build: ./clientD/
    restart: always
    ports:
      - "80:80"
