version: "3"
services:
  mainapi:
   build: ./mainAPID/
   restart: always
   ports:
      - "1800:1800"


  server:
    build: ./serverD/
    restart: always
    ports:
      - "1801:1801"

  client:
    build: ./clientD/
    restart: always
    ports:
      - "80:80"


